print(f"Hello, please enter your sequence below: ")
seq = input()
seq_len = len(seq)
A_count = int(seq.count("A"))
T_count = int(seq.count("T"))
G_count = int(seq.count("G"))
C_count = int(seq.count("C"))
total_count = A_count + T_count + G_count + C_count
GC_value = round((G_count + C_count) / total_count, 2)
RNA_seq = seq.replace("T", "U")
print(f" your sequence: {seq}")
print(f" your RNA sequence: {RNA_seq}")
print(f" your sequence length: {seq_len}")
print(f" your GC: {GC_value}")